"""跨境个人税务助理 · 税务引擎。"""
from .residency import (
    ChinaResidency,
    USResidency,
    TieBreakResult,
    cn_countable_days,
    us_countable_days,
    determine_china_residency,
    determine_us_residency,
    tie_breaker,
)
from .calculator import (
    progressive_tax,
    resident_comprehensive_taxable,
    china_resident_comprehensive_tax,
    china_nonresident_monthly_tax,
    china_business_tax,
    china_dividend_tax,
    china_dividend_tax_bucketed,
    china_a_share_capital_gain_tax,
    us_nra_dividend_tax,
    us_nra_capital_gain_tax,
    us_long_term_capital_gains_rate,
    us_resident_dividend_tax,
    foreign_tax_credit_limit,
    us_progressive_tax,
    us_ordinary_tax,
    us_royalty_withholding_tax,
)

from .obligations import filing_obligations, information_returns
from .cross_border import (
    CrossBorderServiceResult,
    CrossBorderRoyaltyResult,
    cross_border_service_taxability,
    cross_border_royalty_treatment,
)

__all__ = [
    "ChinaResidency",
    "USResidency",
    "TieBreakResult",
    "cn_countable_days",
    "us_countable_days",
    "determine_china_residency",
    "determine_us_residency",
    "tie_breaker",
    "progressive_tax",
    "resident_comprehensive_taxable",
    "china_resident_comprehensive_tax",
    "china_nonresident_monthly_tax",
    "china_business_tax",
    "china_dividend_tax",
    "china_dividend_tax_bucketed",
    "china_a_share_capital_gain_tax",
    "us_nra_dividend_tax",
    "us_nra_capital_gain_tax",
    "us_long_term_capital_gains_rate",
    "us_resident_dividend_tax",
    "foreign_tax_credit_limit",
    "us_progressive_tax",
    "us_ordinary_tax",
    "us_royalty_withholding_tax",
    "filing_obligations",
    "information_returns",
    "CrossBorderServiceResult",
    "CrossBorderRoyaltyResult",
    "cross_border_service_taxability",
    "cross_border_royalty_treatment",
]
